version: '3.9'

services:
  web:
    image: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/2025-fall-festival-be:${GITHUB_SHA}
    container_name: django_app
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION}
      - TRANSLATION_CACHE_TTL_SEC=${TRANSLATION_CACHE_TTL_SEC}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-translation-sa.json
    volumes:
      - ./secrets:/app/secrets  # GCP 키 마운트
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: