version: '3.9'

services:
  web:
    image: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/2025-fall-festival-be:${GITHUB_SHA}
    container_name: django_app
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: