# Generated by Django 5.2.6 on 2025-09-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="description",
        ),
    ]
