# Generated by Django 5.2.6 on 2025-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="type",
            field=models.CharField(
                choices=[("club", "동아리"), ("celebrity", "연예인")],
                default="club",
                max_length=20,
            ),
        ),
    ]
