# Generated by Django 5.2.6 on 2025-09-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stage", "0002_remove_stage_description"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stage",
            name="stage_stage_is_acti_ea4fea_idx",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="is_active",
        ),
    ]
