# Generated by Django 5.2.6 on 2025-09-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FoodTruck", "푸드트럭"),
                            ("Toilet", "화장실"),
                            ("Drink", "주류판매"),
                            ("Store", "편의점"),
                            ("Booth", "부스"),
                        ],
                        default="Booth",
                        max_length=10,
                    ),
                ),
                ("is_night", models.BooleanField(default=False)),
                ("image_url", models.CharField(blank=True, max_length=200, null=True)),
                ("is_liked", models.BooleanField(default=False)),
                ("is_event", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BoothDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("all_table", models.IntegerField()),
                ("usage_table", models.IntegerField()),
                ("can_usage", models.BooleanField(default=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("map_x", models.FloatField()),
                ("map_y", models.FloatField()),
                ("description", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="BoothSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("is_liked", models.BooleanField(default=False)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booth",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booth.location"
            ),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("image_url", models.CharField(blank=True, max_length=200, null=True)),
                ("ingredient", models.IntegerField()),
                ("sold", models.IntegerField()),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
            ],
        ),
    ]
