# Generated by Django 5.2.6 on 2025-09-17 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="operate_date",
            field=models.DateField(default=datetime.date(2025, 9, 17)),
            preserve_default=False,
        ),
    ]
