# Generated by Django 5.2.6 on 2025-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="like_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
