# Generated by Django 5.2.6 on 2025-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
