# Generated by Django 5.2.6 on 2025-09-17 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booth",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="booth",
            name="admin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminuser.admin",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="boothdetail",
            name="booth",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="booth.booth",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
