# Generated by Django 5.2.6 on 2025-09-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0002_booth_like_cnt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booth",
            name="like_cnt",
        ),
        migrations.RemoveField(
            model_name="booth",
            name="operate_date",
        ),
    ]
