# Generated by Django 5.2.6 on 2025-09-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
        ("booth", "0002_booth_operate_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booth",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="booth",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminuser.admin",
            ),
        ),
        migrations.AddField(
            model_name="boothdetail",
            name="booth",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
            ),
            preserve_default=False,
        ),
    ]
