# Generated by Django 5.2.6 on 2025-09-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0003_remove_booth_like_cnt_remove_booth_operate_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="like_cnt",
            field=models.IntegerField(default=0),
        ),
    ]
