# Generated by Django 5.2.6 on 2025-09-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0002_location_description"),
        ("booth", "0002_remove_booth_is_liked_booth_admin_boothdetail_booth_and_more"),
        ("booth", "0003_remove_booth_is_liked_booth_admin_boothdetail_booth"),
    ]

    operations = []
