# Generated by Django 5.2.6 on 2025-09-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0004_booth_like_cnt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="booths/images/"),
        ),
    ]
