# Generated by Django 5.2.6 on 2025-09-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0005_alter_booth_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="menus/images/"),
        ),
    ]
