# Generated by Django 5.2.6 on 2025-09-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0006_alter_like_user_id_alter_menu_image_url"),
        ("booth", "0006_alter_menu_image_url"),
    ]

    operations = []
