# Generated by Django 5.2.6 on 2025-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0007_merge_20250921_0418"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothdetail",
            name="all_table",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdetail",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdetail",
            name="usage_table",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="ingredient",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="sold",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
