# Generated by Django 5.2.6 on 2025-09-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=64)),
                ("field", models.CharField(max_length=64)),
                ("source_lang", models.CharField(max_length=8)),
                ("target_lang", models.CharField(max_length=8)),
                ("source_text", models.TextField()),
                ("translated_text", models.TextField(blank=True, default="")),
                ("provider", models.CharField(default="google", max_length=16)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("checksum", models.CharField(max_length=64)),
                ("meta", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "translation",
                "indexes": [
                    models.Index(fields=["checksum"], name="ix_translation_checksum"),
                    models.Index(fields=["status"], name="ix_translation_status"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_type", "entity_id", "field", "target_lang"),
                        name="uq_translation_target",
                    )
                ],
            },
        ),
    ]
