# Generated by Django 5.2.6 on 2025-09-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="role",
            field=models.CharField(
                choices=[
                    ("Staff", "축제기획단"),
                    ("Stuco", "총학생회"),
                    ("Club", "동아리"),
                    ("Major", "학과"),
                ],
                default="Staff",
                max_length=10,
            ),
        ),
    ]
