# Generated by Django 5.2.6 on 2025-09-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0002_alter_admin_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="uid",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="admin",
            name="uid_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
