# Generated by Django 5.2.6 on 2025-09-20 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminuser", "0003_admin_uid_admin_uid_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="admin",
            name="uid_expires_at",
        ),
        migrations.CreateModel(
            name="AdminUID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=20, unique=True)),
                ("uid_expires_at", models.DateTimeField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uids",
                        to="adminuser.admin",
                    ),
                ),
            ],
        ),
    ]
