# Generated by Django 5.2.6 on 2025-09-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoothEvent",
        ),
    ]
