# Generated by Django 5.2.6 on 2025-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="try_times",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="user_id",
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
    ]
