# Generated by Django 5.2.6 on 2025-09-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_is_started_game_try_times_game_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.sitecoupon",
            ),
        ),
    ]
