# Generated by Django 5.2.6 on 2025-09-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_game_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booth", models.CharField(max_length=100)),
                ("serial_code", models.CharField(max_length=20, unique=True)),
                ("price", models.IntegerField()),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.coupon",
            ),
        ),
        migrations.DeleteModel(
            name="SiteCoupon",
        ),
    ]
