# Generated by Django 5.2.6 on 2025-09-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="writer",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="boothevent",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="boothevent",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
