# Generated by Django 5.2.6 on 2025-09-17 23:37

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_category_boothevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=board.models.image_upload_path
            ),
        ),
    ]
