name: Django CI/CD

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # 1. 프로젝트 폴더로 이동
            cd ~/project

            # 2. 최신 코드 가져오기
            git pull origin main

            # 3. 도커 컨테이너 빌드 & 실행
            docker compose down
            docker compose build
            docker compose up -d
