name: CI/CD to EC2

on:
  push:
    branches: [ 'dev' ]  # dev 브랜치에 푸시되면 배포

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (optional multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 (SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # 배포 디렉토리 이동
            DEPLOY_DIR=~/2025_fall_festival_BE
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # .env 덮어쓰기
            cat > .env <<EOF
IMAGE_TAG=${{ github.sha }}
AWS_REGION=${{ secrets.AWS_REGION }}
AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
SECRET_KEY=${{ secrets.SECRET_KEY }}
DEBUG=false
DOMAIN=${{ secrets.DOMAIN }}
LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}
RUN_MIGRATIONS=true
RUN_COLLECTSTATIC=true
DATABASE_URL=${{ secrets.DATABASE_URL }}
EOF

            # ECR 로그인
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

            # 최신 이미지 pull
            docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
            docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

            # Compose 재시작
            docker-compose pull --ignore-pull-failures
            docker-compose up -d --remove-orphans

            # 마이그레이션/collectstatic (컨테이너 존재할 경우만)
            if docker-compose ps -q web > /dev/null; then
              docker-compose exec -T web python manage.py migrate --noinput || true
              docker-compose exec -T web python manage.py collectstatic --noinput || true
            fi

            # 불필요한 이미지 제거
            docker image prune -af || true
