name: Django CI/CD

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}        # 예: 3.36.xxx.xxx
          username: ${{ secrets.EC2_USERNAME }} # 보통 ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/2025_Fall_Festival
            git pull origin dev
            docker compose down
            docker compose build
            docker compose up -d